apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-instances-set
spec:
  generators:
  - git:
      repoURL: https://github.com/rhilconsultants/NGNIX-API-Gateway-Workshop.git
      revision: GitOps
      directories:
      - path: Workshop-cluster-config/Argocd-instances/layers/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rhilconsultants/NGNIX-API-Gateway-Workshop.git
        targetRevision: GitOps
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-argocd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        
