apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: test-backends
spec:
  template:
    metadata:
      name: test-backends
    spec:
     restartPolicy: Never
     containers:
     - name: test-backends
       image: registry.access.redhat.com/ubi9-minimal:latest
       workingDir: /workspace/output
       command: ["/bin/bash", "-c"]
       args: 
       - 'curl ${BACKEND1_SERVICE_HOST}:${BACKEND1_SERVICE_PORT}/health/liveliness | grep "${TEST}" || exit 1'
       - 'curl ${BACKEND2_SERVICE_HOST}:${BACKEND2_SERVICE_PORT}/health/liveliness | grep "${TEST}" || exit 1'
       - 'curl ${BACKEND3_SERVICE_HOST}:${BACKEND3_SERVICE_PORT}/health/liveliness | grep "${TEST}" || exit 1'
       env:
         - name: TEST
           value: Healty
  backoffLimit: 1