kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-openshift-gitops-argocd-application-controller
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
  annotations:
    argocds.argoproj.io/name: argocd
    argocds.argoproj.io/namespace: openshift-gitops
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-openshift-gitops-argocd-application-controller